version: '3.5'

services:

  memcached:
    image: memcached
    networks:
      - private_network
    restart: always

  mysqldb:
    hostname: mysqldb
    image: mariadb:latest
    networks:
      - private_network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  web:
    build:
      context: .
    networks:
      - public_network
      - private_network
    restart: always
    depends_on:
      - memcached
      - mysqldb
    environment:
      - "VIRTUAL_HOST=${VIRTUAL_HOST:-mysite.com}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-mysite.com}"
      - "PROJECT_DIR=${PROJECT_DIR:-/app}"
      - "DATABASE_URI=${DATABASE_URI:-mysql://myuser:mypass@mysqldb/drupaldb}"
      - "DATABASE_SQL_FILE=${DATABASE_SQL_FILE:-}"
      - "DRUPAL_SITE_NAME=${DRUPAL_SITE_NAME:-Drupal Website}"
      - "DATABASE_ROOT_USER=${DATABASE_ROOT_USER:-root}"
      - "DATABASE_ROOT_PASS=${DATABASE_ROOT_PASS:-root}"
      - "DRUPAL_ADMIN_USERNAME=${DRUPAL_ADMIN_USERNAME:-admin}"
      - "DRUPAL_ADMIN_PASSWORD=${DATABASE_ROOT_USER:-admin}"
      - "DRUPAL_MODULES=${DRUPAL_MODULES:-}"
      - "DRUPAL_THEMES=${DRUPAL_THEMES:-}"
      - "DRUPAL_DEFAULT_THEME=${DRUPAL_DEFAULT_THEME:-}"
      - "DRUPAL_FRONT_PAGE=${DRUPAL_FRONT_PAGE:-}"
      - "DRUPAL_FEATURES_DIR=${DRUPAL_FEATURES_DIR:-}"
      - "DRUPAL_PROJECT=${DRUPAL_PROJECT:-drupal/recommended-project}"
      - "MEMCACHED_HOST=${MEMCACHED_HOST:-memcached}"
      - "MEMCACHED_PORT=${MEMCACHED_PORT:-11211}"
      - "GULP_THEME=${GULP_THEME:-}"
      - "GULP_TARGETS=${GULP_TARGETS:-}"
    volumes:
      - ./:/app
      - ./data/sites:/var/www/html/web/sites
      - ./data/private:/var/www/private
      - ./web/modules:/var/www/html/web/modules/custom
      - ./web/features:/var/www/html/web/modules/custom_features
      - ./web/themes:/var/www/html/web/themes/custom
      # Enable nodejsmodules named volume if your theme needs gulp.
      #- nodejsmodules:/app/web/themes/my_sass_theme/node_modules

volumes:
  nodejsmodules:

networks:
  public_network:
    external:
      name: public_network
  private_network:
    driver: bridge
